@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-np-prod-promo-controls-us-es4-function \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-np-prod-promo-controls-us-es4-function \
                                    --trigger-http --entry-point=run_lambda \
                                    --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=512MB \
                                    --timeout=300 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)