@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-send-email-us-es4-cf \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-send-email-us-es4-cf\
                                    --entry-point=send_email \
                                    --set-env-vars stage=ENVIRONMENT_NAME \
                                    --set-secrets secretKey=dw-np-noreply-email-api-key-sm-us-ct1:1 \
                                    --memory=256MB \
                                    --timeout=180 \
                                    --trigger-http \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)
