@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-source-to-parquet-us-es4-cf --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-source-to-parquet-us-es4-cf \
                                    --entry-point=lambda_handler \
                                    --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=2048MB \
                                    --timeout=500 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-topic=dw-ENVIRONMENT_NAME-parquet-files-generic-pub-sub-us4 \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)
