@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-merchants-raw-files-emailer-us-es4-function-stg-tgr \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=./cloud_functions/dw-merchants-raw-files-emailer-us-es4-function-stg-tgr \
                                    --entry-point=trigger_on_bsi_merchants_upload \
                                    --set-env-vars stage=ENVIRONMENT_NAME,project_id=${env.project_id} \
                                    --memory=1024MB \
                                    --timeout=300 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-event-filters serviceName=storage.googleapis.com \
                                    --trigger-event-filters type=google.cloud.audit.log.v1.written \
                                    --trigger-event-filters methodName=storage.objects.create \
                                    --trigger-event-filters-path-pattern resourceName='/projects/_/buckets/trk-ENVIRONMENT_NAME-sftp-tl-us-es4-gcs/objects/BSI-Merchants/reports/*.xlsx' \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)
