@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-us-bank-custody-doc-us-es4-cf \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-us-bank-custody-doc-us-es4-function \
                                    --entry-point=sftp_handler \
                                    --set-env-vars stage=ENVIRONMENT_NAME,project_id=${env.project_id} \
                                    --set-secrets secretKey=toorak-ENVIRONMENT_NAME-us_bank_file_load-sm-us-ct1:latest \
                                    --memory=2048MB \
                                    --timeout=900 \
                                    --trigger-http \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)