@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-uk-excel-to-parquet-coversion-us-es4-function \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-uk-excel-to-parquet-coversion-us-es4-function \
                                    --entry-point=trigger_on_uk_upload \
                                   --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=1024MB \
                                    --timeout=300 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-event-filters serviceName=storage.googleapis.com \
                                    --trigger-event-filters type=google.cloud.audit.log.v1.written \
                                    --trigger-event-filters methodName=storage.objects.create \
                                    --trigger-event-filters-path-pattern resourceName='/projects/_/buckets/trk-ENVIRONMENT_NAME-sftp-tl-us-es4-gcs/objects/uk_tc/*.xlsx' \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)