@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-pipeline-dashboard-emailer-us-es4-function \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-pipeline-dashboard-emailer-us-es4-function \
                                    --entry-point=lambda_handler \
                                   --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=1024MB \
                                    --timeout=300 \
                                    --trigger-http \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)
