@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-pst-process-us-es4-function \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-pst-process-us-es4-function \
                                    --entry-point=run_pst_monthly \
                                   --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=1024MB \
                                    --timeout=100 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-event-filters serviceName=storage.googleapis.com \
                                    --trigger-event-filters type=google.cloud.audit.log.v1.written \
                                    --trigger-event-filters methodName=storage.objects.create \
                                    --trigger-event-filters-path-pattern resourceName='/projects/_/buckets/dw-ENVIRONMENT_NAME-raw-snapshot-us-es4-gcs/objects/payment-status-tracker/daily-extracts/*/*/*/*.xlsx' \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)