@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-house-canary-trigger-us-es4-cf \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-house-canary-trigger-us-es4-function \
                                    --entry-point=trigger_on_house_canary \
                                    --set-env-vars stage=ENVIRONMENT_NAME,project_id=${env.project_id} \
                                    --memory=1024MB \
                                    --timeout=300 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-event-filters serviceName=storage.googleapis.com \
                                    --trigger-event-filters type=google.cloud.audit.log.v1.written \
                                    --trigger-event-filters methodName=storage.objects.create \
                                    --trigger-event-filters-path-pattern resourceName='/projects/_/buckets/dw-ENVIRONMENT_NAME-house-canary-us-es4-gcs/objects/input/*/*.csv' \
                                    --trigger-service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)