@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-fci-api-data-us-es4-cf-2 \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-fci-api-data-us-es4-cf-2 \
                                    --entry-point=helloHttp \
                                    --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=1024MB \
                                    --timeout=1900 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-http \
                                    --set-secrets secretKey=toorak-ENVIRONMENT_NAME-fci_data_fetch-sm-us-ct1:1 \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)