@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-fci-api-data-us-es4-cf \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=./cloud_functions/dw-fci-api-data-us-es4-cf \
                                    --entry-point=hello_http \
                                   --set-env-vars stage=ENVIRONMENT_NAME \
                                    --memory=1024MB \
                                    --timeout=1800 \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --trigger-http \
                                    --set-secrets secretKey=toorak-ENVIRONMENT_NAME-fci_data_fetch-sm-us-ct1:1 \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"]]
dwServerless(config)
