@Library('jenkins-shared-library') _
def config = [serverlessCommand: ["dw-ENVIRONMENT_NAME-upload-report-to-box-us-es4-function \
                                    --gen2 \
                                    --runtime=python311 \
                                    --region=us-east4 --source=dw-upload-report-to-box-us-es4-function\
                                    --entry-point=check_pipeline_run \
                                    --set-env-vars stage=ENVIRONMENT_NAME,project_id=${env.project_id} \
                                    --memory=1024MB \
                                    --timeout=2000 \
                                    --trigger-http \
                                    --service-account=dw-ENVIRONMENT_NAME-cloud-function-sa@${env.project_id}.iam.gserviceaccount.com \
                                    --update-labels product=dw  \
                                    --update-labels environment=ENVIRONMENT_NAME \
                                    --update-labels deployedby=cicd"], githubUrl: "https://github.com/Toorak-Capital/dw-cloud-functions.git"]
serverlessDeploy(config)